### ISSUE TITLE
unnesessary css and js loading everywhere :(

### ISSUE THREAD

**Issue by Ontario7** [kunalnagar/custom-404-pro#28]
Hi, 
thanks for the great plugin.
Just wonder why css and js you load on every existing page?
There is the way to check first if page exists and shut down loading those files.
Is it so hard?

Regards.

**Comment by kunalnagar** [comment]
Hi @Ontario7 

Thanks for the heads up. I will try and get this sorted out in the next release as I don't think it's too big a deal. The CSS and JS should only impact the admin dashboard and should have no impact on the performance of your website.

**Comment by kunalnagar** [comment]
Hi @Ontario7 

New plugin version released: v2.1.0 This should fix the unnecessary CSS and JS loading everywhere.

Thanks!

**Comment by Ontario7** [comment]
Dear Kunal, Thank you for the info.I do not see the plugin on WP plugins repository yet.   Kind regards,Vladimir RybinskyEuro Segway Prague+420 776 337 560https://www.eurosegway.cz/   18.11.2017, 06:35, "Kunal Nagar" <notifications@github.com>:Hi @Ontario7New plugin version released: v2.1.0 This should fix the unnecessary CSS and JS loading everywhere.Thanks!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by kunalnagar** [comment]
Hi @Ontario7 

You should see the update now. Let me know if you still don't get it.

**Comment by Ontario7** [comment]
Hi, Now I did update is as well, thanks. But the bug issue #28 still exists.... I see the code<link rel='stylesheet' id='custom-404-pro-css' href='https://www.eurosegway.es/wp-content/plugins/custom-404-pro/public/css/custom-404-pro-public.css?ver=1.0.0' type='text/css' media='all' /> and <script type='text/javascript' src='https://www.eurosegway.es/wp-content/plugins/custom-404-pro/public/js/custom-404-pro-public.js?ver=1.0.0'></script> On all the pages of the website, not only on 404 page. That's abusive for google search, it is extra scripts not needed on pages :(  Kind regards,Vladimir RybinskyEuro Segway Prague+420 776 337 560https://www.eurosegway.cz/   18.11.2017, 12:02, "Kunal Nagar" <notifications@github.com>:Hi @Ontario7You should see the update now. Let me know if you still don't get it.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by kunalnagar** [comment]
Hi @Ontario7 

Those files are empty, they don't contain any code. I have removed the JS and CSS from loading on all other ADMIN pages only. I can remove the public ones in the next update as well but that should not have any impact on your site.

**Comment by Ontario7** [comment]
Thank you, hope in next update it would be corrected.  Feel free to contact us at any time.  Kind regards,Vladimir RybinskyEuro Segway Prague+420 776 337 560https://www.eurosegway.cz/18.11.2017, 12:40, "Kunal Nagar" <notifications@github.com>:Hi @Ontario7
Those files are empty, they don't contain any code. I have removed the JS and CSS from loading on all other ADMIN pages only. I can remove the public ones in the next update as well but that should not have any impact on your site.
